### ISSUE TITLE
Any news about submission?

### ISSUE THREAD

**Issue by lawpdas** [Spritea/GMOT40#3]
Hi,
I want to evaluate my work on GMOT40, but the submission page is unavailable.
Could you provide an official toolkit for evaluation?

**Comment by Spritea** [comment]
In fact, since we adopt those widely used metrics, you could use any code base that implements these metrics, like [py-motmetrics](https://github.com/cheind/py-motmetrics).

Since the test set is also available, you can test it locally, The submission page is only for demonstration, not for evaluation.

We are still thinking about it, please stay tuned.
